### ISSUE TITLE
缺少 requests module

### ISSUE THREAD

**Issue by ivanshih68** [sanlii829/naerExamDownload#2]
Traceback (most recent call last):
  File "/Users/ivan/Downloads/naerExamDownload-main/naerExamPaperDownload.py", line 1, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'

**Comment by sanlii829** [comment]
在程式中使用了 requests 套件，但 Python 找不到該套件。你可以在Python的終端輸入以下命令來安裝這個套件。
pip install requests

**Comment by ivanshih68** [comment]
> 在程式中使用了 requests 套件，但 Python 找不到該套件。你可以在Python的終端輸入以下命令來安裝這個套件。 pip install requests

成功運行了 謝謝
