### ISSUE TITLE
副檔名格式錯誤

### ISSUE THREAD

**Issue by januschiang-moneydj** [sanlii829/naerExamDownload#3]
![image](https://github.com/user-attachments/assets/c0d61d36-9501-425c-8fa3-479118a108cb)
如圖，有些學校提供的副檔名未必是pdf，例如這個是給doc，程式未考慮副檔名非pdf的case，
造成抓下來的檔案無法開啟，雖然改副檔名就會好，但其實使用者不會發現此問題。

建議download_pdf func. 可以把副檔名切出來，貼到輸出檔名file_name尾端。

感謝貢獻!

**Comment by sanlii829** [comment]
感謝你，我的確沒發現除了pdf檔案以外還有其它格式的問題。
在Python Scripts中已經修正了這個問題，再次謝謝你的醒醒。
